webapp/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Prefrences
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .constants import PASS_REGEX
import re

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                return render_template("login.html", user=current_user, message='Invalid e-mail and password.')
        else:
            return render_template("login.html", user=current_user, message='No such account exists.')
    return render_template("login.html", user=current_user, message=None)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            return render_template("signup.html", user=current_user, message='User already exists. Try logging in!')
        else:
            pattern = re.compile(PASS_REGEX)
            match = re.search(pattern, password)
            if not match:
                return render_template("signup.html", user=current_user, message='Password must be atleast 6 characters long consisting atleast one lowercase, uppercase, numberic digit and a symbol.')
            else:
                new_user = User(email=email, password=generate_password_hash(password), isadmin=False)
                db.session.add(new_user)
                db.session.commit()
                return redirect(url_for('auth.login'))
    return render_template("signup.html", user=current_user, message=None)

@auth.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_pass():
    cats = Prefrences.query.filter_by(user_id=current_user.id).all()
    if request.method == 'POST':
        password = request.form.get('password')
        new_pass = request.form.get('new_password')

        pattern = re.compile(PASS_REGEX)
        match = re.search(pattern, new_pass)

        if not match:
            return render_template("change_pass.html", user=current_user, message='Password must be atleast 6 characters long consisting atleast one lowercase, uppercase, numberic digit and a symbol.', preferences=cats)
        if check_password_hash(current_user.password, password):
            current_user.password = generate_password_hash(new_pass, method='sha256')
            db.session.commit()
            return redirect(url_for('views.home'))
        else:
            return render_template('change_pass.html', user=current_user, message='Current password is invalid. Please try again!', preferences=cats)
    return render_template('change_pass.html', user=current_user, message=None, preferences=cats)

webapp/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user
from .models import User, Prefrences, News
from . import db
from .constants import CATEGORIES, SITE_MAP
from .helper import utils

views = Blueprint('views', __name__)

@views.route('/dumpusers')
def dumpusers():
    gmail_addresses = [
        'bytegeek@gmail.com',
        'codemaster@gmail.com',
        'techwhiz@gmail.com',
        'cybergeek@gmail.com',
        'digitech@gmail.com',
        'gadgetguru@gmail.com',
        'innovatorx@gmail.com',
        'computernerd@gmail.com',
        'robotlover@gmail.com',
        'cybersleuth@gmail.com',
        'techsavvy@gmail.com',
        'datapioneer@gmail.com',
        'codehacker@gmail.com',
        'techjunkie@gmail.com',
        'techiegenius@gmail.com',
        'geekgirl@gmail.com',
        'cyberspacepro@gmail.com',
        'digitalwizard@gmail.com',
        'hackermind@gmail.com',
        'technomaster@gmail.com'
    ]
    password = 'Geeks12@'
    for email in gmail_addresses:
        new_user = User(email=email, password=generate_password_hash(password), isadmin=False)
        db.session.add(new_user)
        db.session.commit()
    print(User.query.all())
    return redirect(url_for('auth.logout'))

@views.route('/')
@login_required
def home():
    cats = Prefrences.query.filter_by(user_id=current_user.id).all()
    return redirect('/national')

@views.route('/account', methods=['GET', 'POST'])
@login_required
def pref():
    if request.method == 'POST':
        add_pref = request.form.get('add')
        rem_pref = request.form.get('rem')

        if add_pref != 'Choose a preference':
            prefs = Prefrences(cat=add_pref, user_id=current_user.id)
            db.session.add(prefs)
            db.session.commit()

        if not rem_pref == 'Choose a preference':
            prefs = Prefrences.query.filter_by(user_id=current_user.id)
            for item in prefs:
                if item.cat == rem_pref:
                    db.session.delete(item)
                    db.session.commit()
        
    cats = Prefrences.query.filter_by(user_id=current_user.id).all()
    rem_cats = [item.cat for item in cats]
    add_cats = list(set(CATEGORIES).symmetric_difference(set(rem_cats)))

    return render_template('pref.html', user=current_user, add_cats=add_cats, rem_cats=rem_cats, preferences=cats)

@views.route('/<string:category>')
@login_required
def news_cat(category):
    cats = Prefrences.query.filter_by(user_id=current_user.id).all()
    category = category.title()
    news = News.query.filter_by(category=category).all()
    math = (len(news) // 2) - ((len(news) // 2) % 3)
    news = news[:math]
    # for i in range(len(news) // 2):
    #     print(news[i].news)
    # print(len(news))
    return render_template('index.html', user=current_user, preferences=cats, data=news, papers=SITE_MAP[category])

@views.route('/admin')
@login_required
def admin_panel():
    if not current_user.isadmin:
        return 'You cannot access this page', 404
    cats = Prefrences.query.filter_by(user_id=current_user.id).all()
    users = User.query.all()
    return render_template('panel.html', user=current_user, users=users, preferences=cats)

@views.route('/make_admin/<int:id>')
@login_required
def make_admin(id):
    id = int(id)
    user = User.query.filter_by(id=id).first()
    user.isadmin = True
    db.session.commit()
    return redirect(url_for('views.admin_panel'))

@views.route('/remove_admin/<int:id>')
@login_required
def remove_admin(id):
    id = int(id)
    user = User.query.filter_by(id=id).first()
    user.isadmin = False
    db.session.commit()
    return redirect(url_for('views.admin_panel'))

@views.route('/delete_user/<int:id>')
@login_required
def delete_user(id):
    id = int(id)
    user = User.query.filter_by(id=id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('views.admin_panel'))

@views.route('/api/<string:category>')
def api(category):
    result = []
    records = News.query.filter_by(category=category.title()).all()
    print(len(records))
    for record in records:
        temp = {
            'headline': record.news,
            'source': record.link,
            'site': record.site
        }
        result.append(temp)
    data = {
        'category': category,
        'data': result
    }
    return jsonify(data)

# @views.route('/xyz')
# def xyz():
#     news = News.query.all()
#     print(len(news))
#     return '<p></p>'

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <header class="text-gray-700 bg-gray-100 body-font">
      <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" href={{ url_for('views.home') }}>
          <span class="ml-3 text-xl">Newsly</span>
        </a>

        {% if user.is_authenticated %}
        <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-300 flex flex-wrap items-center text-base justify-center">
          {% if preferences %}
            {% for preference in preferences %}
              <a class="mr-5 hover:text-gray-900" href={{ preference.cat|lower }}>{{ preference.cat }}</a>
            {% endfor %}
          {% else %}
            {% for category in ['National', 'World', 'Sports', 'Entertainment', 'Business', 'Technology', 'Politics'] %}
            <a class="mr-5 hover:text-gray-900" href={{ category|lower }}>{{ category }}</a>
            {% endfor %}
          {% endif %}
        </nav>
        {% if user.isadmin %}
          <a href={{ url_for('views.admin_panel') }}
            <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Admin
            </button>
          </a>
        {% endif %}
        <a href={{ url_for('views.pref') }}
          <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Account
          </button>
        </a>
        <a href={{ url_for('auth.logout') }}
          <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Logout!
          </button>
        </a>
        {% else %}
        <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-300	flex flex-wrap items-center text-base justify-center">
          <a class="mr-5 hover:text-gray-900" href="/">Home</a>
        </nav>
        <a href={{ url_for('auth.login') }}
          <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Login!
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
          </button>
        </a>
        <a href={{ url_for('auth.signup') }}
          <button class="inline-flex items-center border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">Sign Up!
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
          </button>
        </a>
        {% endif %}
      </div>
    </header>
    {% block content %}
    {% endblock %}
    <footer class="bg-gray-200 text-gray-700 text-center py-4">
        Made with ❤️ by Vivek, Bhavesh, Dweep.
    </footer>
    <script>
      if ( window.history.replaceState ) {
      window.history.replaceState( null, null, window.location.href );
      }
    </script>
</body>
</html>

webapp/templates/change_pass.html
{% extends "base.html" %}
{% block title %}Account settings{% endblock %}
{% block content %}
<section class="flex justify-center items-center h-screen bg-white">
    <div class="max-w-md w-full bg-gray-100 rounded p-6 space-y-4"><br><br>
      <form method="POST">
        <div class="mb-4">
            <p class="text-gray-600">Password setting</p>
            <h2 class="text-xl font-bold text-black">Change your account password here!</h2>
        </div>
        <div>
            <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="password" id="password" name="password" placeholder="Current password" required>
        </div><br>
        <div>
            <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="password" id="new_password" name="new_password" placeholder="New password" required>
            {% if message %}
            <p class="text-gray-600 text-xs mt-2 mb-4">{{ message }}</p>
            {% endif %}
          </div><br>
        <div>
            <button type="submit" class="w-full py-4 bg-blue-600 hover:bg-blue-700 rounded text-sm font-bold text-gray-50 transition duration-200">Change Password</button>
        </div>
        <div class="mt-4">
          <p class="text-left text-blue-600"><a href={{ url_for('views.pref') }}>Back to preferences</a></p>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

webapp/templates/index.html
{% extends "base.html" %}
{% block title %}Newsly{% endblock %}
{% block content %}
<section class="text-gray-900 bg-white body-font">
  {% for paper in papers %}
    <div class="container px-5 pt-10 pb-0 mx-auto flex flex-wrap">
        <div class="flex flex-col text-center w-full mb-20">
          <h1 class="sm:text-3xl text-2xl font-medium title-font text-black">{{ paper }}</h1>
        </div>
        <div class="flex flex-wrap -m-4">
          {% for news in data %}
            {% if news.site == paper %}
              <div class="p-4 md:w-1/3">
                <div class="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                  <div class="flex-grow">
                    <p class="leading-relaxed text-base">{{ news.news }}</p>
                    <a class="mt-3 text-purple-700 inline-flex items-center" href={{ news.link }} target="_blank">Read More
                      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
        </div>
    </div>
  {% endfor %}
  <div class="container px-5 pt-10 pb-10 mx-auto flex flex-wrap"></div>
</section>
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<section class="flex justify-center items-center h-screen bg-white">
  <div class="max-w-md w-full bg-gray-100 rounded p-6 space-y-4"><br><br>
    <form method="POST">
      <div class="mb-4">
          <p class="text-gray-600">Login</p>
          <h2 class="text-xl font-bold text-black">Login to your account here!</h2>
      </div>
      <div>
          <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="email" id="email" name="email" placeholder="Email" required>
      </div><br>
      <div>
          <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="password" id="password" name="password" placeholder="Password" required>
          {% if message %}
          <p class="text-gray-600 text-xs mt-2 mb-4">{{ message }}</p>
          {% endif %}
          <div><br>
          <button type="submit" class="w-full py-4 bg-blue-600 hover:bg-blue-700 rounded text-sm font-bold text-gray-50 transition duration-200">Login</button>
      </div>
      <div class="mt-4">
        <p class="text-left text-blue-600"><span class="text-black">Not registered?</span> <a href={{ url_for('auth.signup') }}>Create account</a></p>
      </div>
    </form>
  </div>
</section>
{% endblock %}

webapp/templates/panel.html
{% extends "base.html" %}
{% block title %}Newsly{% endblock %}
{% block content %}
<section class="text-gray-700 body-font bg-gray-100">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h2 class="text-xs text-indigo-400 tracking-widest font-medium title-font mb-1">ADMIN PANEL</h2>
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Manage Users</h1>
      </div>
      <div class="flex flex-wrap">
        {% for user in users %}
        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-300">
            <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">{{ user.email }}</h2>
            <p class="leading-relaxed text-base mb-4">Admin Status: {{ user.isadmin }}</p>
            <a class="text-indigo-400 inline-flex items-center pe-3" href={{ url_for('views.delete_user', id=user.id) }}>Delete user!</a>
            {% if user.isadmin %}
            <a class="text-indigo-400 inline-flex items-center" href={{ url_for('views.remove_admin', id=user.id) }}>Remove admin!</a>
            {% else %}
                <a class="text-indigo-400 inline-flex items-center" href={{ url_for('views.make_admin', id=user.id) }}>Make admin!</a>
            {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

webapp/templates/pref.html
{% extends "base.html" %}
{% block title %}Newsly{% endblock %}
{% block content %}
<section class="flex justify-center items-center h-screen bg-white">
    <div class="max-w-md w-full bg-gray-100 rounded p-6 space-y-4"><br><br>
      <form method="POST">
        <div class="mb-4">
            <p class="text-gray-600">Preferences</p>
            <h2 class="text-xl font-bold text-black">Edit your news preferences here!</h2>
        </div>
        <div>
            <label for="countries" class="block mb-2 text-sm font-medium text-gray-900">Add a preference</label>
            <select id="countries" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" id="add" name="add">
            <option selected>Choose a preference</option>
            {% for cat in add_cats %}
            <option value={{ cat }}>{{ cat }}</option>
            {% endfor %}
            </select>
        </div><br>
        <div>
            <label for="countries" class="block mb-2 text-sm font-medium text-gray-900">Remove a preference</label>
            <select id="countries" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" id="rem" name="rem">
            <option selected>Choose a preference</option>
            {% for cat in rem_cats %}
            <option value={{ cat }}>{{ cat }}</option>
            {% endfor %}
            </select>
        </div><br>
        <div>
            <button type="submit" class="w-full py-4 bg-blue-600 hover:bg-blue-700 rounded text-sm font-bold text-gray-50 transition duration-200">Make changes</button>
        </div>
        <div class="mt-4">
            <p class="text-left text-blue-600"><a href={{ url_for('auth.change_pass') }}>Change your password here!</a></p>
        </div>
      </form>
    </div>
</section>
{% endblock %}

webapp/templates/signup.html
{% extends "base.html" %}
{% block title %}Create an account!{% endblock %}
{% block content %}
<section class="flex justify-center items-center h-screen bg-white">
  <div class="max-w-md w-full bg-gray-100 rounded p-6 space-y-4"><br><br>
    <form method="POST">
      <div class="mb-4">
          <p class="text-gray-600">Sign Up</p>
          <h2 class="text-xl font-bold text-black">Create an account here!</h2>
      </div>
      <div>
          <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="email" id="email" name="email" placeholder="Email" required>
      </div><br>
      <div>
          <input class="w-full p-4 text-sm bg-gray-50 focus:outline-none border border-gray-200 rounded text-gray-600" type="password" id="password" name="password" placeholder="Password" required>
          {% if message %}
          <p class="text-gray-400 text-xs mt-2 mb-4">{{ message }}</p>
          {% endif %}
        </div><br>
      <div>
          <button type="submit" class="w-full py-4 bg-blue-600 hover:bg-blue-700 rounded text-sm font-bold text-gray-50 transition duration-200">Sign Up</button>
      </div>
      <div class="mt-4">
        <p class="text-center text-blue-600"><a href={{ url_for('auth.login') }}>Already have an account?</a></p>
      </div>
    </form>
  </div>
</section>
{% endblock %}